feat: 1주차 필수과제
AND-SOPT-ANDROID/daehyeon-kim pull request #2
Opened 2024-10-11 05:12 UTC by wjdrjs00

## Related issue 🛠
- closed #1 

## Work Description ✏️
- 회원가입 뷰
    - 회원가입 시 이메일, 비밀번호 형식 검증
    - 회원가입 성공 조건 불일치시 스낵바 알림과 텍스트필드 에러표시
    - show 버튼을 통한 비밀번호 확인 가능
    - 이메일, 비밀번호 입력시 회원가입 버튼 활성화
    - 회원가입 성공 시 SignInActivity로 전환
- 로그인 뷰
    - 회원가입 버튼 누를 시 SignUpActivity로 전환
    - 회원가입 시 사용한 이메일 registerForActivityResult와 putExtra를 사용해서 로그인
    - 로그인 성공조건에 따른 토스트 메시지 추가
- MY 뷰
    - 닉네임 회원가입시 사용한 이메일 표시

## Screenshot 📸
<img src="https://github.com/user-attachments/assets/17bfe008-de8c-4e2b-804b-a0b1ce20b568" width="360"/>

## Uncompleted Tasks 😅

## To Reviewers 📢
열심히 해봤습니다.. registerForActivityResult, putExtra는 처음 사용해봤는데 알맞게 적용한건지 궁금하네요..🤔

2024-10-12 10:58 UTC, l2hyunwoo commented
안녕하세요. 명예 OB 리뷰어 이현우입니다. 앞으로 N번의 과제동안 잘 부탁드리겠습니다. 🙇🏻 

해당 PR의 리뷰는 금잔디조 내 모든 분들의 리뷰가 완료된 후 작성하도록 하겠습니다.

2024-10-12 21:03 UTC, MinseoSONG reviewed
1주차인데도 깔끔하게 코드 잘 짜신 것 같아요 .. 좋겠ㄷ ㅏ ,,
2주차도 같이 화이팅해봐요 !

2024-10-12 21:03 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +        }
와 background color를 Scaffold의 containerColor로 준건가요? 신기해용

2024-10-12 21:03 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +                color = Color.Gray
string으로 따로 추출해서 쓰면 좋을 거 같아요 !

2024-10-12 21:03 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/signin/SignInActivity.kt
> +                                showSnackbar("이메일 또는 비밀번호가 일치하지 않습니다.")
상황별 다른 snackbar가 나오도록 하셨네요 ! 전 그냥 로그인 실패, 성공만 해놨는데 .. 참고하겠습니다 ㅎㅎ

2024-10-12 21:03 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/signup/SignUpScreen.kt
> +        InfoText("로그인, 비밀번호 찾기, 알림에 사용되니 정확한 이메일을 입력해 주세요.")
이걸 따로 component로 빼둔 이유가 있을까요 ??

2024-10-12 21:03 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/util/Validation.kt
> +    email.isNotEmpty() && password.length >= 8
각각의 조건을 함수로 다 따로 설정하셨군요 ! 신기해용

2024-10-13 02:33 UTC, beom84 approved these changes
고생하셨습니다! 코드가 정말 깔끔하군요!

2024-10-13 02:33 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/my/MyActivity.kt
> +        val userEmail = intent.getStringExtra("email") ?: ""
key값은 상수화 하는게 좋다는 소문을 들었습니다!

2024-10-13 02:33 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +@Composable
오 topbar도 다 만드셨군요.. topbar는 따로 component 패키지에 안넣은 이유가 있나요?

2024-10-13 02:33 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +                        text = if (showPassword) "hide" else "show",
저는 text를 두개 만들었는데.. 이렇게 하겠습니다

2024-10-13 02:33 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/signup/SignUpScreen.kt
> +private fun SignUpBottomBar(
bottom bar를 이용해서 만드셨군요! 하나 배워갑니다.

2024-10-13 02:33 UTC, beom84 commented on app/src/main/java/org/sopt/and/util/Validation.kt
> +fun isEmailValid(email: String): Boolean =
email은 안드에서 제공하는 android.util.Patterns.EMAIL_ADDRESS.matcher(Email).matches() 
라는게 있더라고요.. 좋은지는 모르지만 남겨봅니다

2024-10-13 03:35 UTC, Hyobeen-Park reviewed
1주차 과제 수고하셨습니다!!! 벌써 topBar, bottomBar를 모두 사용하시다니...!!! 짱이네요👍🏻

2024-10-13 03:35 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/component/textField/WaaveTextField.kt
> +    visualTransformation: VisualTransformation = VisualTransformation.None
오~~ 꼼꼼하네요

2024-10-13 03:35 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/my/MyActivity.kt
> +        val userEmail = intent.getStringExtra("email") ?: ""
맞아요!! `"email"`과 같은 키값은 다른 액티비티에서도 쓰이니까 상수로 빼면 바로 가져다 쓸 수 있습니다!

2024-10-13 03:35 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +    TopAppBar(
오!! 이부분 탑바로 구현하셨네요!! 이유가 궁금합니다!!!

2024-10-13 03:35 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/signin/SignInActivity.kt
> +                                showSnackbar("이메일 또는 비밀번호가 일치하지 않습니다.")
저도 로그인 실패 / 성공만 해뒀는데 참고하겠습니다ㅎㅎ

2024-10-13 03:35 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/signin/SignInActivity.kt
> +                            inputEmail == userEmail && inputPassword == userPassword -> {
회원가입을 하지 않은 상태에서 바로 로그인 버튼을 누르면 input data와 user data가 둘 다 `""`라서 로그인이 될 것 같은데 혹시 이거 확인해보셨나요??

2024-10-13 03:35 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +                .height(50.dp)
높이를 고정하면 기기의 폰트를 키웠을 때 텍스트가 버튼 크기보다 커지는 문제가 생길 수 있어요!! `.height` 를 고정하지 않고 버튼의 높이를 조절할 수 있는 방법은 무엇이 있을까요?

2024-10-13 03:35 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/signup/SignUpScreen.kt
> +            isError = email.isNotEmpty() && !isEmailValid(email)
혹시 isEmpty()와 isBlank()의 차이점을 알고 계신가요?? 자주 쓰이는 함수라 알아두면 좋답니다😊

2024-10-13 03:35 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/util/Validation.kt
> +    val minLength = password.length in 8..20
길이 조건 (8, 20) 도 상수화 하면 유지보수 할 때 편할 것 같아요!

2024-10-13 03:35 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/signup/component/InfoText.kt
> +    text: String
modifier를 추가하면 컴포넌트를 사용할 때 Spacer를 사용하지 않고도 패딩을 넣어줄 수 있어요!!

2024-10-13 03:35 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/util/Validation.kt
> +fun isEmailValid(email: String): Boolean =
오 이건 저도 안써봤는데..!! 한 번 사용해 봐야겠네요ㅎㅎ 감사해요!!

2024-10-13 06:49 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +                color = Color.Gray
넵! 적용해보겠습니다~~

2024-10-13 06:51 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signup/SignUpScreen.kt
> +        InfoText("로그인, 비밀번호 찾기, 알림에 사용되니 정확한 이메일을 입력해 주세요.")
이메일과 비밀번호 정보? 부분 아이콘 + 텍스트가 중복되는거 같아서 따로 분리해봤습니다!! 
<img width="421" alt="스크린샷 2024-10-13 15 50 44" src="https://github.com/user-attachments/assets/55f39c4e-0e56-459b-b69e-e0dd3f0322de">

2024-10-13 06:52 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/my/MyActivity.kt
> +        val userEmail = intent.getStringExtra("email") ?: ""
넵 적용해보겠습니다!!

2024-10-13 06:55 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +@Composable
1주차 과제로만 봤을때, 확장성이 크게 안느껴져서 따로 component화 필요성이 없다고 판단했습니다!!
좋은 방법이 아닐 수도 있지만, 앱 확장되면 분석해서 component화 해보겠습니다!

2024-10-13 06:56 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/util/Validation.kt
> +fun isEmailValid(email: String): Boolean =
처음 알게된 부분인데 한번 공부해보고 어떤 이점이 있는지 알아보겠습니다!!!

2024-10-13 06:58 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/util/Validation.kt
> +    val minLength = password.length in 8..20
넵 적용해보겠습니다!

2024-10-13 07:11 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signin/SignInActivity.kt
> +                            inputEmail == userEmail && inputPassword == userPassword -> {
헉,, 확인해보니 로그인이 되군요,, 수정하겠습니다!

2024-10-13 07:15 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +    TopAppBar(
topbar를 사용할지 row를 사용할지 고민하다가 topbar의 actions가 rowscope라 활용하면 좀더 icon 선언에 편리할거 같단 생각에 topbar를 사용했습니다.
근데 title 부분이 높이가 좀 고정되어있는거 같아서 적합한 방법이 아닌가? 하는 생각은 들었습니다!

2024-10-13 07:18 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signup/component/InfoText.kt
> +    text: String
Spacer를 사용하면 이 사이에 간격이 있단 사실을 좀 더 명확하게 파악할 수 있지 않을까?란 생각에 사용해봤는데, 패딩을 사용하는 방식이 좀 컴포지션 측면에서 효율적일까요??

2024-10-13 07:26 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signup/SignUpScreen.kt
> +            isError = email.isNotEmpty() && !isEmailValid(email)
디테일하게 신경쓰지 못했던 부분인데 이번기회에 확인해보겠습니다!

✅ 확인해보니 isEmpty()는 문자열의 길이만 확인하고 isBlank()는 추가로 문자열의 공백여부를 확인한다는 차이를 알았습니다.
기존 코드는 공백이 들어가면 isNotEmpty() 가 true를 반환할 수 있기 때문에 isNotBlank()의 사용이 더 적합한거 같습니다!!

2024-10-13 07:39 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +                .height(50.dp)
.wrapContentHeight()를 활용해서 해결 가능하단 사실을 알게되었습니다.
2주차 리펙토링 단계에서 적용해보겠습니다!!!

2024-10-13 16:39 UTC, l2hyunwoo requested changes
안녕하세요! 안드로이드 명예오비 이현우입니다.

우선 첫 주차임에도 불구하고 깔끔하게 로직과 UI 잘 구성하셨습니다. 너무 고생많으셨어요. YB이신데 컴포즈로 코드를 어느정도 짜신 것 같은 느낌이 나는군요. 정말 훌륭하십니다.

짜그마한 성능 이슈나 컴포즈 사용패턴 위주로 리뷰 남겼습니다. (+ 코드에 대한 질문 약간?) 참고해보시면 좋을 것 같아요. 2차 과제 이전에 피드백 반영하시면 추가리뷰 달아드리도록 하겠습니다.

2024-10-13 16:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/component/textField/WaaveTextField.kt
> +    trailingIcon: @Composable (() -> Unit)? = null,
Q) default value로 null을 주는 것과 그렇지 않은 것의 차이를 알고 계신가요?

2024-10-13 16:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/component/textField/WaaveTextField.kt
> +    visualTransformation: VisualTransformation = VisualTransformation.None
👍🏻

2024-10-13 16:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/signin/SignInActivity.kt
> +    }
- 컴포즈에서도 registerForActivityResult를 사용할 수 있습니다. (rememberLauncherForActivityResult)
- 화면 재구성시에 (onDestroy -> onCreate) userEmail, userPassword는 어떻게 될까요?

2024-10-13 16:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/signin/SignInActivity.kt
> +                                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK)
Q) 이 플래그의 의미를 알고 계신가요?

2024-10-13 16:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +    onSignInClick: (String, String, (String) -> Unit) -> Unit = { _, _, _ -> },
각각의 패러미터가 의미하고 있는 바를 잘 모르겠네요...어떻게 하면 각 패러미터의 의미를 더 잘 드러낼 수 있을까요?

2024-10-13 16:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +                onSignUpClick = { onSignUpClick() }
```suggestion
                onSignUpClick = onSignUpClick
```

이렇게 작성해도 됩니다

2024-10-13 16:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +    padding: PaddingValues,
이걸 사용하기 보단 modifier 주입받는게 더 좋을 것 같습니다! 어차피 컨테이너의 스타일을 외부에서 조정해야한다면 아예 외부에서 스타일을 전부 컨트롤할 수 있는 여지를 주는게 이후 수정할때에도 더 편하실 거에요

2024-10-13 16:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +        Spacer(modifier = Modifier.padding(3.dp))
```suggestion
        Spacer(modifier = Modifier.height(6.dp))
```

2024-10-13 16:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/signup/SignUpActivity.kt
> +                                }
```suggestion
                                val resultIntent = Intent()
                                    .putExtra("email", email)
                                    .putExtra("password", password)
```

2024-10-13 16:39 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/util/Validation.kt
> +    "[a-zA-Z0-9._-]+@[a-z]+\\.+[a-z]+".toRegex().matches(email)
[이 리뷰](https://github.com/AND-SOPT-ANDROID/minseo-song/pull/2#discussion_r1798440281) 참고해서 보시면 좋을 것 같아요

2024-10-14 04:52 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/component/textField/WaaveTextField.kt
> +    trailingIcon: @Composable (() -> Unit)? = null,
커스텀 컴포넌트를 구성하면서 단순 필수적으로 구현해야 하는 것과 선택적으로 구현 해야하는 것을 구분할때 기본값을 주어 구분하는 정도로만 생각했습니다. 이번 리뷰를 통해 placeholderValue: String = "" 의 기본값을 null로 선언해도 작동에는 문제가 없단 사실을 통해 기본값 선언에 대한 차이를 알아보았습니다. 이 과정에서 
- 기본값을 ""와 같이 빈문자열로 선언한 경우는 파라미터가 옵셔널이긴 하지만 항상 유요한 값을 가지며, 이는 항상 기본값을 가지므로 컴포넌트 내부에서 null 체크 없이 안전하게 이용할 수 있단 사실을 알게되었습니다.
- 기본값을 null로 선언한 경우는 파라미터가 완전한 옵셔널을 가지게 되며, 사용자가 이 파라미터를 제공하지 않아도 컴포넌트를 사용할 수 있습니다. 사용시에는 컴포넌트 내부에서 이 파라미터를 사용할 때 null 체크가 필요하다는 사실을 알게 되었습니다.

필수적이지 않은 기능에는 null default를, 항상 필요하지만 기본값을 제공하고 싶은 기능에는 non-null default를 사용하는 것이 일반적인 패턴이라는 사실을 확인할 수 있었습니다!!!
결국 제가 구현한 WaaveTextField는 이메일과, 비밀번호 두 곳에서 사용되고 있지만, trailingIcon부분은 비밀번호에서만 사용되고 있기 때문에 기존에 구현되어있는 기본값을 null로 주는 방식이 적합하다고 생각할 수 있었고, 사용하는곳에서 null체크가 필요성을 알 수 있었습니다.

2024-10-14 06:25 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signin/SignInActivity.kt
> +    }
현재 코드는 화면 재구성(ex. 가로모드)시에 userEmail, userPassword이 들고있는 값이 손실되는 문제가 발생한다는 사실을 알게 되었습니다. Activity의 인스턴스가 메모리에서 제거되는 과정에서 userEmail, userPassword가 손실되고 새로운 Activity의 인스턴스가 생성되기 때문입니다.
이러한 문제를 방지하기 위해 onSaveInstanceState()를 활용해서 상태를 저장하고 onCreate시에 상태를 복원하는 방법이 있음을 알게되었습니다!!

2024-10-14 06:40 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signin/SignInActivity.kt
> +    }
`rememberLauncherForActivityResult`는 처음 알게된 내용입니다!!
알아보니 `rememberLauncherForActivityResult`는 Compose 기반의 UI에서 액티비티 결과를 처리할 때 사용됨을 알게 되었습니다. 사용의 이점은 compose의 상태 관리 시스템과 톰합되어 Activity의 결과를 compose 내에서 직접 처리하여 보다 효율적인 상태관리가 가능하다 합니다. 실제로 userEmail, userPassword를 remember와 mutableStateOf를 사용하여 관리할 수 있고 이는 onSaveInstanceState()의 사용 없이도 회전과 같은 구성 변경 시 상태가 자동으로 유지된다고 합니다!
이번에 처음 접하는 방식이라 1주차 과제에서는 registerForActivityResult()과 onSaveInstanceState()를 활용하여 구현하고 2주차 과정에서 좀 더 공부해보고 리펙터링 하는 과정을 가져보겠습니다!!

2024-10-14 06:49 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signin/SignInActivity.kt
> +                                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK)
이번 세미나를 통해 flag를 처음 접해서 '새로운 Activity가 생성되면서 이전까지의 Activity는 전부 삭제시켜서 다시 로그인 화면으로 돌아감을 방지'하는 정도로 알고있습니다!
(알맞게 알고있는지와 혹시 추가로 더 학습해야할 부분이 있을지 궁금합니다!!)

2024-10-14 07:22 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +    padding: PaddingValues,
넵! 확장성을 위해 modifier를 주입받는 방식으로 적용해보겠습니다!

2024-10-14 08:13 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +    onSignInClick: (String, String, (String) -> Unit) -> Unit = { _, _, _ -> },
`data class SignInInfo(
    val email: String?,
    val password: String?,
)` 이와 같은 SignInInfo 클래스를 선언하고, 명시적 선언을 활용해서 `onSignInClick: (SignInInfo, snackbarMessage: (String) -> Unit) -> Unit = { _, _ -> }` 이렇게 구현해봤습니다!

sealed class 또는 Result 패턴을 도입하여 좀더 명확한 표현이 가능하단 방법이 있다는 사실도 알게되었습니다. (이 방법은 추가 학습 후 구현해보겠습니다!!)

2024-10-15 11:09 UTC, MinseoSONG approved these changes

2024-10-16 01:03 UTC, jihyunniiii reviewed
고생하셨슴당

2024-10-16 01:03 UTC, jihyunniiii commented on app/src/main/AndroidManifest.xml
> +        </activity>
exported 속성에 대해 알아보시면 좋을 것 같습니당

2024-10-16 01:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
> +) {
Composable 함수에서 파라미터 순서는 다음의 순서를 따르는 것을 권장합니다!
1. 필수값
2. 생성자
3. 선택값

2024-10-16 01:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/signup/SignUpScreen.kt
> +                    "\nWavve를 즐길 수 있어요!",
```suggestion
            text = "이메일과 비밀번호만으로\nWavve를 즐길 수 있어요!",
```
그냥 이렇게 적을 수도 있을 것 같네요!

2024-10-16 01:03 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/signup/component/InfoText.kt
> +    text: String
개인마다 다르겠지만 저는 보통 해당 컴포넌트가 얼마만큼의 크기를 가져야 하는지에 따라 padding을 사용할지, Spacer를 사용할지를 결정하는 것 같아요!
예를 들면 공백값을 포함하는 만큼의 크기를 가져야 하는 경우 (터치영역을 고려하는 등이 여기 속하겠죠?)에는 패딩을 아니면 Spacer를 사용합니다.

2024-10-16 09:48 UTC, wjdrjs00 commented on app/src/main/AndroidManifest.xml
> +        </activity>
✅ 특정 컴포넌트가 다른 애플리케이션에서 접근 여부를 제어할 때 사용됨을 알았습니다!

2024-10-16 12:51 UTC, Hyobeen-Park approved these changes
1차 과제 수고하셨습니다!! 2차 과제도 화이팅..!!

2024-10-16 22:40 UTC, merged